package com.htmlapp.wrapper;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.webkit.WebView;
import android.webkit.WebViewClient;

/**
 * Wrapper Activity generated by "صانع تطبيقات ميوز" build server.
 * Shows a splash screen, then loads the user's HTML from assets.
 * Deliberately avoids AppCompat and any R references so the APK
 * can be built with aapt2 + d8 only (no resource class needed).
 */
public class MainActivity extends Activity {

    private WebView webView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        webView = new WebView(this);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setDomStorageEnabled(true);
        webView.getSettings().setAllowFileAccess(true);
        webView.getSettings().setAllowContentAccess(true);
        webView.getSettings().setMediaPlaybackRequiresUserGesture(false);
        // Keep all navigation inside the app instead of opening a browser.
        webView.setWebViewClient(new WebViewClient());
        setContentView(webView);

        // Splash screen first, then the app content.
        webView.loadUrl("file:///android_asset/splash.html");
        new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
            @Override
            public void run() {
                webView.loadUrl("file:///android_asset/www/index.html");
            }
        }, 2000);
    }

    @Override
    public void onBackPressed() {
        if (webView != null && webView.canGoBack()) {
            webView.goBack();
        } else {
            super.onBackPressed();
        }
    }
}
